<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cheque Management Report</title>
    <style>
        @page {
            margin: 20px 25px 50px 25px; /* top, right, bottom, left */
        }
        body {
            font-family: sans-serif;
            font-size: 9px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 4px;
            text-align: left;
            vertical-align: top;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .font-semibold {
            font-weight: 600;
        }
        h1, h2 {
            margin-bottom: 0;
            text-align: center;
        }
        h1 {
            font-size: 16px;
        }
        h2 {
            font-size: 12px;
            color: #555;
            margin-bottom: 5px;
        }
        .filter-info {
            font-size: 9px;
            margin-bottom: 10px;
            text-align: center;
            color: #333;
        }
        tfoot tr {
            background-color: #f9f9f9;
            font-weight: bold;
        }
        .footer {
            position: fixed;
            bottom: -30px; /* Adjust if footer is cut off */
            left: 0px;
            right: 0px;
            height: 30px;
            text-align: center;
            line-height: 30px;
            font-size: 9px;
            color: #777;
            border-top: 1px solid #ddd;
        }
        .page-number:before {
            content: "Page " counter(page);
        }
        .status-pending {
            background-color: #fef9c3; /* yellow-100 */
            color: #713f12; /* yellow-800 */
        }
        .status-bounced {
            background-color: #fee2e2; /* red-100 */
            color: #991b1b; /* red-800 */
        }
        .status-default {
            background-color: #f3f4f6; /* gray-100 */
            color: #1f2937; /* gray-800 */
        }
        .days-overdue {
            background-color: #fee2e2; /* red-100 */
            color: #991b1b; /* red-800 */
        }
        .days-due-today {
            background-color: #fef9c3; /* yellow-100 */
            color: #713f12; /* yellow-800 */
        }
        .days-left {
            background-color: #dcfce7; /* green-100 */
            color: #166534; /* green-800 */
        }
        .badge {
            display: inline-block;
            padding: 2px 6px;
            font-size: 8px;
            font-weight: 600;
            line-height: 1;
            text-align: center;
            white-space: nowrap;
            vertical-align: baseline;
            border-radius: .25rem;
        }
    </style>
</head>
<body>
    <div class="footer">
        Generated by: {{ $generatedBy }} on {{ $generatedAt->format('d-M-Y h:i A') }} - <span class="page-number"></span>
    </div>

    <h1>Cheque Management Report</h1>
    @if($search || $maturityStartDate || $maturityEndDate)
        <div class="filter-info">
            <strong>Filters Applied:</strong>
            @if($search) Search: "{{ $search }}" | @endif
            @if($maturityStartDate) Maturity From: {{ \Carbon\Carbon::parse($maturityStartDate)->format('d-M-Y') }} | @endif
            @if($maturityEndDate) Maturity To: {{ \Carbon\Carbon::parse($maturityEndDate)->format('d-M-Y') }} @endif
        </div>
    @else
        <div class="filter-info">No filters applied.</div>
    @endif

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Tenant</th>
                <th>Contract</th>
                <th>Property</th>
                <th>Cheque No</th>
                <th>Bank</th>
                <th>Maturity Date</th>
                <th class="text-right">Amount</th>
                <th>Status</th>
                <th>Days Balance</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($cheques as $cheque)
                <tr>
                    <td>{{ $cheque->id }}</td>
                    <td>{{ $cheque->contract->tenant->name }}</td>
                    <td>{{ $cheque->contract->name }}</td>
                    <td>{{ $cheque->contract->property->name }}</td>
                    <td>{{ $cheque->cheque_no }}</td>
                    <td>{{ $cheque->cheque_bank }}</td>
                    <td>{{ $cheque->cheque_date->format('d M Y') }}</td>
                    <td class="text-right">{{ number_format($cheque->amount, 2) }}</td>
                    <td>
                        @php
                            $statusClass = 'status-default';
                            if ($cheque->status === 'PENDING') $statusClass = 'status-pending';
                            if ($cheque->status === 'BOUNCED') $statusClass = 'status-bounced';
                        @endphp
                        <span class="badge {{ $statusClass }}">{{ ucfirst(strtolower($cheque->status)) }}</span>
                    </td>
                    <td>
                        @php
                            $daysDiff = now()->startOfDay()->diffInDays($cheque->cheque_date->startOfDay(), false);
                            $daysClass = '';
                            $daysText = '';
                            if($daysDiff < 0){
                                $daysText = round(abs($daysDiff)) . ' days overdue';
                                $daysClass = 'days-overdue';
                            } elseif($daysDiff == 0){
                                $daysText = 'Due today';
                                $daysClass = 'days-due-today';
                            } else {
                                $daysText = round($daysDiff) . ' days left';
                                $daysClass = 'days-left';
                            }
                        @endphp
                        <span class="badge {{ $daysClass }}">{{ $daysText }}</span>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="10" class="text-center" style="padding: 10px;">No cheques found matching your criteria.</td>
                </tr>
            @endforelse
        </tbody>
        @if ($cheques->isNotEmpty() && isset($grandTotals) && $grandTotals['count'] > 0)
            <tfoot>
                <tr>
                    <td colspan="7" class="font-semibold">Grand Totals ({{ $grandTotals['count'] }} Cheques):</td>
                    <td class="text-right font-semibold">{{ number_format($grandTotals['amount'], 2) }}</td>
                    <td colspan="2"></td> {{-- Empty cells for remaining columns --}}
                </tr>
            </tfoot>
        @endif
    </table>

</body>
</html>
