<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cheque Status Report</title>
    <style>
        @page {
            margin: 20px 25px 50px 25px; /* top, right, bottom, left */
        }
        body { font-family: sans-serif; font-size: 9px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #ddd; padding: 4px; text-align: left; vertical-align: top; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .text-right { text-align: right; }
        h1 { font-size: 14px; text-align: center; margin-bottom: 5px; }
        h2 { font-size: 12px; color: #555; margin-bottom: 10px; text-align: center; }
        .date-range { font-size: 9px; margin-bottom: 10px; text-align: center; color: #555; }
        tfoot tr { background-color: #f9f9f9; font-weight: bold; }
        .footer { position: fixed; bottom: -30px; left: 0px; right: 0px; height: 30px; text-align: center; line-height: 30px; font-size: 9px; color: #777; border-top: 1px solid #ddd; }
        .page-number:before { content: "Page " counter(page); }
        .status-cleared { color: green; }
        .status-pending { color: orange; }
        .status-bounced { color: red; }
        /* Add other status colors if needed */
    </style>
</head>
<body>
    <div class="footer">
        Generated by: {{ $generatedBy }} on {{ $generatedAt->format('d-M-Y h:i A') }} - <span class="page-number"></span>
    </div>

    <h1>Cheque Status Report</h1>
    <h2>Type: {{ ucfirst($currentFilter) }}</h2>
    @if($currentFilter === 'cleared' && ($startDate || $endDate))
        <p class="date-range">
            Date Range: {{ $startDate ? \Carbon\Carbon::parse($startDate)->format('d-M-Y') : 'N/A' }} to {{ $endDate ? \Carbon\Carbon::parse($endDate)->format('d-M-Y') : 'N/A' }}
        </p>
    @endif

    <table>
        <thead>
            <tr>
                @foreach ($columns as $column)
                    <th class="{{ str_contains(strtolower($column), 'amount') ? 'text-right' : '' }}">{{ $column }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
             @forelse ($reportData as $index => $receipt)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $receipt->property_name }}</td>
                    <td>{{ $receipt->tenant_name }}</td>
                    <td>{{ $receipt->contract_name }}</td>
                    <td>{{ $receipt->cheque_no }}</td>
                    <td>{{ $receipt->cheque_bank }}</td>
                    @if($currentFilter === 'cleared')
                        <td>{{ $receipt->deposit_date ? \Carbon\Carbon::parse($receipt->deposit_date)->format('d-M-Y') : 'N/A' }}</td>
                    @else
                        <td>{{ $receipt->cheque_date ? \Carbon\Carbon::parse($receipt->cheque_date)->format('d-M-Y') : 'N/A' }}</td>
                    @endif
                    <td class="text-right">{{ number_format($receipt->amount, 2) }}</td>
                     <td>
                        <span class="status-{{ strtolower($receipt->status) }}">
                            {{ ucfirst(strtolower($receipt->status)) }}
                        </span>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($columns) }}" style="text-align: center; padding: 10px;">No {{ strtolower($currentFilter) }} cheques found matching criteria.</td>
                </tr>
            @endforelse
        </tbody>
        @if ($reportData->isNotEmpty())
            <tfoot>
                <tr>
                     <td colspan="7">Grand Totals ({{ $grandTotals['cheques'] }} Cheques):</td>
                    <td class="text-right">{{ number_format($grandTotals['amount'], 2) }}</td>
                    <td></td>
                </tr>
            </tfoot>
        @endif
    </table>
</body>
</html>
