<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contracts Report</title>
    <style>
        @page {
            margin: 20px 25px 50px 25px; /* top, right, bottom, left */
        }
        body { font-family: sans-serif; font-size: 9px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #ddd; padding: 4px; text-align: left; vertical-align: top; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .text-right { text-align: right; }
        h1 { font-size: 14px; text-align: center; margin-bottom: 5px; }
        h2 { font-size: 12px; color: #555; margin-bottom: 10px; text-align: center; }
        .date-range { font-size: 9px; margin-bottom: 10px; text-align: center; color: #555; }
        tfoot tr { background-color: #f9f9f9; font-weight: bold; }
        .footer { position: fixed; bottom: -30px; left: 0px; right: 0px; height: 30px; text-align: center; line-height: 30px; font-size: 9px; color: #777; border-top: 1px solid #ddd; }
        .page-number:before { content: "Page " counter(page); }
        .status-ongoing { color: blue; } /* Adjust as needed */
        .status-closed { color: gray; }
    </style>
</head>
<body>
    <div class="footer">
        Generated by: {{ $generatedBy ?? 'System' }} on {{ isset($generatedAt) ? $generatedAt->format('d-M-Y h:i A') : now()->format('d-M-Y h:i A') }} - <span class="page-number"></span>
    </div>

    <h1>Contracts Report</h1>
    <h2>Type: {{ ucfirst($currentFilter ?? 'N/A') }}</h2>
    @if($startDate || $endDate)
        <p class="date-range">
            Date Range (Start Date): {{ $startDate ? \Carbon\Carbon::parse($startDate)->format('d-M-Y') : 'N/A' }} to {{ $endDate ? \Carbon\Carbon::parse($endDate)->format('d-M-Y') : 'N/A' }}
        </p>
    @endif

    <table>
        <thead>
            <tr>
                @if (!empty($columns))
                    @foreach ($columns as $column)
                        <th class="{{ str_contains(strtolower($column), 'amount') ? 'text-right' : '' }}">{{ $column }}</th>
                    @endforeach
                @endif
            </tr>
        </thead>
        <tbody>
             @if (!empty($reportData))
                @forelse ($reportData as $index => $contract)
                    @php
                        $endDate = $contract->cend ? \Carbon\Carbon::parse($contract->cend)->startOfDay() : null;
                        $isClosed = $contract->validity === 'NO';
                        $statusText = $isClosed ? 'Closed' : 'Ongoing';
                    @endphp
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $contract->property_name }}</td>
                        <td>{{ $contract->tenant_name }}</td>
                        <td>{{ $contract->name ?? 'N/A' }}</td>
                        <td>{{ $contract->cstart ? \Carbon\Carbon::parse($contract->cstart)->format('d-M-Y') : 'N/A' }}</td>
                        <td>{{ $endDate ? $endDate->format('d-M-Y') : 'N/A' }}</td>
                        <td class="text-right">{{ number_format($contract->amount ?? 0, 2) }}</td>
                        <td>
                             <span class="status-{{ $isClosed ? 'closed' : 'ongoing' }}">
                                {{ $statusText }}
                            </span>
                        </td>
                        {{-- Conditional column --}}
                        <td>
                             @if (!$isClosed && $endDate)
                                @php $diffInDays = now()->startOfDay()->diffInDays($endDate, false); @endphp
                                {{ $diffInDays >= 0 ? $diffInDays . ' days remaining' : 'Late by ' . abs($diffInDays) . ' days' }}
                            @elseif ($isClosed && $endDate)
                                {{ $endDate->format('d-M-Y') }}
                            @else
                                N/A
                            @endif
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="{{ !empty($columns) ? count($columns) : 1 }}" style="text-align: center; padding: 10px;">
                            No {{ strtolower($currentFilter ?? 'N/A') }} contracts found matching criteria.
                        </td>
                    </tr>
                @endforelse
            @endif
        </tbody>
        @if (!empty($reportData) && $reportData->isNotEmpty() && !empty($grandTotals))
            <tfoot>
                <tr>
                     <td colspan="6">Grand Totals ({{ $grandTotals['contracts'] ?? 0 }} Contracts):</td>
                    <td class="text-right">{{ number_format($grandTotals['amount'] ?? 0, 2) }}</td>
                    <td colspan="{{ $currentFilter === 'ongoing' ? 2 : 1 }}"></td>
                </tr>
            </tfoot>
        @endif
    </table>
</body>
</html>
