<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Security Deposit Report</title>
    <style>
        @page {
            margin: 20px 25px 50px 25px; /* top, right, bottom, left - adjusted bottom for footer */
        }
        body {
            font-family: sans-serif;
            font-size: 10px;
            /* Removed margin: 20px; as @page handles it */
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 5px; /* Slightly reduced padding */
            text-align: left;
            vertical-align: top;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .text-right {
            text-align: right;
        }
        .font-semibold {
            font-weight: 600;
        }
        h1, h2 {
            margin-bottom: 5px;
        }
        h1 {
            font-size: 16px;
            text-align: center;
        }
        h2 {
            font-size: 14px;
            color: #555;
            margin-bottom: 10px; /* Reduced */
            text-align: center;
        }
        .date-range {
             font-size: 9px;
             margin-bottom: 10px;
             text-align: center;
             color: #555;
        }
        tfoot tr {
            background-color: #f9f9f9;
            font-weight: bold;
        }
        .footer {
            position: fixed;
            bottom: -30px; /* Adjusted position relative to @page margin */
            left: 0px;
            right: 0px;
            height: 30px;
            text-align: center;
            line-height: 30px;
            font-size: 9px;
            color: #777;
            border-top: 1px solid #ddd;
        }
        .page-number:before {
            content: "Page " counter(page);
        }
        /* Add any other A4-specific styles */
    </style>
</head>
<body>
    <div class="footer">
        Generated by: {{ $generatedBy }} on {{ $generatedAt->format('d-M-Y h:i A') }} - <span class="page-number"></span>
    </div>

    <h1>Security Deposit Report</h1>
    <h2>Type: {{ ucfirst($currentFilter) }}</h2>
    {{-- Add date range if applicable --}}
    @if($currentFilter === 'settled' && ($startDate || $endDate))
        <p class="date-range">
            Date Range: {{ $startDate ? \Carbon\Carbon::parse($startDate)->format('d-M-Y') : 'N/A' }} to {{ $endDate ? \Carbon\Carbon::parse($endDate)->format('d-M-Y') : 'N/A' }}
        </p>
    @endif

    <table>
        <thead>
            <tr>
                @foreach ($columns as $column)
                    <th class="{{ str_contains(strtolower($column), 'amount') || str_contains(strtolower($column), 'contracts') || str_contains(strtolower($column), 'deductions') || str_contains(strtolower($column), 'refunded') || str_contains(strtolower($column), 'held') || str_contains(strtolower($column), 'received') ? 'text-right' : '' }}">{{ $column }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @if ($currentFilter === 'settled')
                @forelse ($reportData as $index => $item)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $item->property_name }}</td>
                        <td>{{ $item->tenant_name }}</td>
                        <td>{{ $item->contract_name }}</td>
                        <td class="text-right">1</td>
                        <td class="text-right">{{ number_format($item->deposit_received, 2) }}</td>
                        <td class="text-right">{{ number_format($item->deduction_amount, 2) }}</td>
                        <td class="text-right">{{ number_format($item->deposit_refunded, 2) }}</td>
                        <td class="text-right font-semibold">{{ number_format($item->net_held, 2) }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="{{ count($columns) }}" style="text-align: center; padding: 10px;">No settled deposit data found matching criteria.</td>
                    </tr>
                @endforelse
            @elseif ($currentFilter === 'unsettled')
                @forelse ($reportData as $index => $contract)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $contract->property->name ?? 'N/A' }}</td>
                        <td>{{ $contract->name }}</td>
                        <td>{{ $contract->tenant->name ?? 'N/A' }}</td>
                        <td class="text-right">{{ number_format($contract->total_deposit_received, 2) }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="{{ count($columns) }}" style="text-align: center; padding: 10px;">No unsettled deposit data found matching criteria.</td>
                    </tr>
                @endforelse
            @endif
        </tbody>
        @if ($reportData->isNotEmpty())
            <tfoot>
                <tr>
                    <td colspan="{{ $currentFilter === 'settled' ? 4 : 4 }}">Grand Totals:</td>
                    @if ($currentFilter === 'settled')
                        <td class="text-right">{{ $grandTotals['contracts'] }}</td>
                        <td class="text-right">{{ number_format($grandTotals['received'], 2) }}</td>
                        <td class="text-right">{{ number_format($grandTotals['deductions'], 2) }}</td>
                        <td class="text-right">{{ number_format($grandTotals['refunded'], 2) }}</td>
                        <td class="text-right">{{ number_format($grandTotals['net_held'], 2) }}</td>
                    @elseif ($currentFilter === 'unsettled')
                        <td class="text-right">{{ number_format($grandTotals['deposit_received'], 2) }}</td>
                    @endif
                </tr>
            </tfoot>
        @endif
    </table>

</body>
</html>
