<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Tenant Ledger Report</title>
    <style>
        body { font-family: sans-serif; font-size: 10px; margin: 20px; }
        /* .page-break { page-break-after: always; } */ /* Removed page break style */
        .header, .footer { text-align: center; margin-bottom: 15px; }
        .report-title { font-size: 16px; font-weight: bold; margin-bottom: 5px; }
        .filters { font-size: 9px; color: #555; margin-bottom: 15px; text-align: center; border-bottom: 1px solid #ccc; padding-bottom: 10px; }
        .contract-block { margin-bottom: 20px; padding: 10px; border: 1px solid #ccc; border-radius: 5px; /* page-break-inside: avoid; <- Can keep or remove, less relevant now */ }
        .contract-header { background-color: #f2f2f2; padding: 8px; margin-bottom: 10px; font-size: 11px; font-weight: bold; border-radius: 3px; display: block; /* Ensure it behaves like a block for layout */ }
        .contract-header span { display: inline-block; margin-right: 15px; white-space: nowrap; }
        .receipts-title { font-size: 12px; font-weight: bold; margin-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 5px; }
        th, td { border: 1px solid #ddd; padding: 4px; text-align: left; vertical-align: top; }
        th { background-color: #f9f9f9; font-weight: bold; }
        .text-right { text-align: right; }
        .status-pending { background-color: #fff3cd; }
        .status-cleared { background-color: #d4edda; }
        .status-bounced, .status-cancelled { background-color: #f8d7da; }
        .badge { display: inline-block; padding: 2px 5px; font-size: 9px; font-weight: bold; border-radius: 4px; }
        .badge-active { background-color: #28a745; color: white; }
        .badge-closed { background-color: #dc3545; color: white; }
        .footer { font-size: 8px; color: #777; text-align: center; position: fixed; bottom: 0px; left: 0px; right: 0px; height: 30px; }
    </style>
</head>
<body>

    <div class="header">
        <div class="report-title">Tenant Ledger Report</div>
        <div style="font-size: 9px;">Generated By: {{ $reportGeneratedBy }} on {{ $generationDate }}</div>
    </div>

    <div class="filters">
        Filters Applied:
        Status [{{ ucfirst($filterStatus) }}],
        Receipt Date Range [{{ $filterStartDate ? \Carbon\Carbon::parse($filterStartDate)->format('d-M-Y') : 'N/A' }} - {{ $filterEndDate ? \Carbon\Carbon::parse($filterEndDate)->format('d-M-Y') : 'N/A' }}],
        Search Term [{{ !empty($filterSearchTerm) ? $filterSearchTerm : 'N/A' }}]
        @if($isSingleContractReport)
        (Displaying specific contract based on search)
        @endif
    </div>

    @if ($contracts->isEmpty())
        <p>No data available based on the selected filters.</p>
    @else
        @foreach ($contracts as $contract)
            <div class="contract-block">
                {{-- Contract Details Header --}}
                <div class="contract-header">
                    <span>Contract Name: {{ $contract->name ?? 'N/A' }}</span>
                    <span>Tenant: {{ $contract->tenant->name ?? 'N/A' }}</span>
                    <span>Rent: {{ number_format($contract->amount, 0) }}</span>
                    <span>Start: {{ $contract->cstart ? $contract->cstart->format('d-M-Y') : 'N/A' }}</span>
                    <span>End: {{ $contract->cend ? $contract->cend->format('d-M-Y') : 'N/A' }}</span>
                    <span>Status:
                        @if ($contract->validity === 'YES')
                            <span class="badge badge-active">ACTIVE</span>
                        @else
                            <span class="badge badge-closed">{{ strtoupper($contract->validity ?? 'CLOSED') }}</span>
                        @endif
                    </span>
                </div>

                <div class="receipts-title">Receipt History</div>
                @if($contract->receipts->isEmpty())
                    <p style="font-size: 9px; color: #777;">No receipts found for this contract within the selected date range.</p>
                @else
                    <table>
                        <thead>
                            <tr>
                                <th>Trans ID</th>
                                <th>Purpose</th>
                                <th>Type</th>
                                <th>Narration</th>
                                <th>Ch Status</th>
                                <th>Ch No</th>
                                <th>Bank</th>
                                <th class="text-right">Amount</th>
                                <th>Chq Date</th>
                                <th>Deposit On</th>
                                <th>Deposit AC</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($contract->receipts as $receipt)
                                <tr>
                                    <td>{{ $receipt->id }}</td>
                                    <td>{{ $receipt->receipt_category }}</td>
                                    <td>{{ $receipt->payment_type }}</td>
                                    <td>{{ $receipt->narration }}</td>
                                    <td @class(['status-pending' => $receipt->status === 'PENDING', 'status-cleared' => $receipt->status === 'CLEARED', 'status-bounced' => $receipt->status === 'BOUNCED' || $receipt->status === 'CANCELLED'])>{{ $receipt->status ?? 'N/A' }}</td>
                                    <td>{{ $receipt->cheque_no ?? 'N/A' }}</td>
                                    <td>{{ $receipt->cheque_bank ?? 'N/A' }}</td>
                                    <td class="text-right">{{ number_format($receipt->amount, 0) }}</td>
                                    <td>
                                        @if ($receipt->payment_type === 'CHEQUE' && $receipt->cheque_date)
                                            {{ $receipt->cheque_date->format('d-M-Y') }}
                                        @elseif ($receipt->receipt_date)
                                            {{ $receipt->receipt_date->format('d-M-Y') }}
                                        @else
                                            N/A
                                        @endif
                                    </td>
                                    <td>{{ $receipt->deposit_date ? $receipt->deposit_date->format('d-M-Y') : 'N/A' }}</td>
                                    <td>{{ $receipt->deposit_account ?? 'N/A' }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                @endif
            </div>
            {{-- Removed page break logic --}}
            {{--
            @if (!$loop->last)
                <div class="page-break"></div>
            @endif
            --}}
        @endforeach
    @endif

    <div class="footer">
        Generated By: {{ $reportGeneratedBy }} - PropertyLivewire
    </div>

</body>
</html>
